### ISSUE TITLE
Non ASCII Email Decoding Error

### ISSUE THREAD

**Issue by pke11y** [nautobot/nautobot-plugin-circuit-maintenance#152]
### Environment

- Python version: 3.8
- Nautobot version: 1.1.3
- nautobot-circuit-maintenance version: 0.3.2

### Expected Behavior

Extract email from mailbox with  attachments (attachment is encoded in UTF-16).

### Observed Behavior

Notification retrieval failed with unhandled Exception.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nautobot_circuit_maintenance/handle_notifications/sources.py", line 610, in get_notifications
    raw_notifications = source.receive_notifications(job_logger, since_date)
  File "/usr/local/lib/python3.8/site-packages/nautobot_circuit_maintenance/handle_notifications/sources.py", line 389, in receive_notifications
    raw_notification = self.fetch_email(job_logger, msg_id)
  File "/usr/local/lib/python3.8/site-packages/nautobot_circuit_maintenance/handle_notifications/sources.py", line 339, in fetch_email
    return self.process_email(job_logger, email_message)
  File "/usr/local/lib/python3.8/site-packages/nautobot_circuit_maintenance/handle_notifications/sources.py", line 288, in process_email
    raw_payload=email_message.as_bytes(),
  File "/usr/local/lib/python3.8/email/message.py", line 178, in as_bytes
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/local/lib/python3.8/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/local/lib/python3.8/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/local/lib/python3.8/email/generator.py", line 218, in _dispatch
    meth(msg)
  File "/usr/local/lib/python3.8/email/generator.py", line 276, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "/usr/local/lib/python3.8/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/local/lib/python3.8/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/local/lib/python3.8/email/generator.py", line 218, in _dispatch
    meth(msg)
  File "/usr/local/lib/python3.8/email/generator.py", line 436, in _handle_text
    super(BytesGenerator,self)._handle_text(msg)
  File "/usr/local/lib/python3.8/email/generator.py", line 253, in _handle_text
    self._write_lines(payload)
  File "/usr/local/lib/python3.8/email/generator.py", line 155, in _write_lines
    self.write(line)
  File "/usr/local/lib/python3.8/email/generator.py", line 410, in write
    self._fp.write(s.encode('ascii', 'surrogateescape'))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 916: ordinal not in range(128)
```

### Steps to Reproduce

1. Execute job to retrieve emails from mail source.
2.
3.

**Comment by pke11y** [comment]
It looks like we cannot handle mails with the following encoding 
```
MIME-Version: 1.0

Content-Transfer-Encoding: 7bit
```

Mails with encoding `utf-8` work fine.
```
MIME-Version: 1.0

Content-Type: text/plain; charset=UTF-8
```
